app:
  secret_key:
  log_dir: /snakemake/logs
  web_dir: web
  workflow_dir: /snakemake/workflows
  workflow_definition_dir: /snakemake/workflow_definitions_git
  workflow_definition_repo: https://github.com/KrKOo/snakemake-web-workflows.git
  workflow_definition_branch: main
  oidc_url:
  oidc_client_id:
  oidc_client_secret:
  oidc_audience:

snakemake:
  snakemake_container_image: krkoo/snakemake:0.1
  snakemake_jobs: 3 
  default_storage_prefix: s3://default
  tes_url:
  storage_s3_endpoint_url:
  storage_s3_access_key:
  storage_s3_secret_key:
celery:
  broker_url: amqp://user:password@rabbitmq-service:5672//
  result_backend: redis://redis-service:6379/0
mongo:
  mongodb_uri: mongodb://user:password@localhost/snakemake-web