import uuid

FILE = "out101"

rule test:
    input: 
        FILE 
    output:
        FILE + "_out"
    shell:
        "cat {input} >> {output}"

rule test1:
    output:
        FILE
    shell:
        "touch {output} && echo hello > {output}"